<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public function run()
    {
        // Electronics & Mobile Products
        $electronicsProducts = [
            [
                'seller_id' => 1,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 1,
                'name' => 'iPhone 15 Pro Max 256GB',
                'slug' => 'iphone-15-pro-max-256gb',
                'description' => 'Latest iPhone 15 Pro Max with A17 Pro chip, titanium design, and advanced camera system. Features 6.7-inch Super Retina XDR display.',
                'b2c_price' => 1199.99,
                'b2c_compare_price' => 1299.99,
                'b2b_price' => 1099.99,
                'b2b_moq' => 2,
                'stock_quantity' => 50,
                'category' => 'Mobile Phones',
                'brand' => 'Apple',
                'model' => 'iPhone 15 Pro Max',
                'specifications' => ['storage' => '256GB', 'color' => 'Natural Titanium', 'display' => '6.7-inch', 'chip' => 'A17 Pro'],
                'images' => [
                    'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500&auto=format&fit=crop'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.8,
                'verification_status' => 'approved',
                'category_id' => 1,
            ],
            [
                'seller_id' => 1,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 1,
                'name' => 'Samsung Galaxy S24 Ultra 512GB',
                'slug' => 'samsung-galaxy-s24-ultra-512gb',
                'description' => 'Premium Samsung Galaxy S24 Ultra with S Pen, 200MP camera, and AI-powered features. 6.8-inch Dynamic AMOLED display.',
                'b2c_price' => 1299.99,
                'b2c_compare_price' => 1399.99,
                'b2b_price' => 1199.99,
                'b2b_moq' => 2,
                'stock_quantity' => 35,
                'category' => 'Mobile Phones',
                'brand' => 'Samsung',
                'model' => 'Galaxy S24 Ultra',
                'specifications' => ['storage' => '512GB', 'color' => 'Titanium Black', 'display' => '6.8-inch', 'camera' => '200MP'],
                'images' => [
                    'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=500&auto=format&fit=crop'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.7,
                'verification_status' => 'approved',
                'category_id' => 1,
            ],
            [
                'seller_id' => 1,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 1,
                'name' => 'MacBook Pro 16-inch M3 Pro',
                'slug' => 'macbook-pro-16-inch-m3-pro',
                'description' => 'Powerful MacBook Pro with M3 Pro chip, 16-inch Liquid Retina XDR display, and up to 22 hours of battery life.',
                'b2c_price' => 2499.99,
                'b2c_compare_price' => 2699.99,
                'b2b_price' => 2299.99,
                'b2b_moq' => 1,
                'stock_quantity' => 25,
                'category' => 'Laptops',
                'brand' => 'Apple',
                'model' => 'MacBook Pro 16-inch',
                'specifications' => ['chip' => 'M3 Pro', 'memory' => '18GB', 'storage' => '512GB SSD', 'display' => '16.2-inch'],
                'images' => [
                    'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=500&auto=format&fit=crop'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.9,
                'verification_status' => 'approved',
                'category_id' => 2,
            ],
            [
                'seller_id' => 1,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 1,
                'name' => 'Sony WH-1000XM5 Wireless Headphones',
                'slug' => 'sony-wh-1000xm5-wireless-headphones',
                'description' => 'Industry-leading noise canceling wireless headphones with 30-hour battery life and premium sound quality.',
                'b2c_price' => 399.99,
                'b2c_compare_price' => 449.99,
                'b2b_price' => 349.99,
                'b2b_moq' => 5,
                'stock_quantity' => 80,
                'category' => 'Audio',
                'brand' => 'Sony',
                'model' => 'WH-1000XM5',
                'specifications' => ['type' => 'Over-ear', 'battery' => '30 hours', 'noise_canceling' => true, 'wireless' => true],
                'images' => [
                    'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=500&auto=format&fit=crop'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.6,
                'verification_status' => 'approved',
                'category_id' => 3,
            ],
        ];

        // Fashion & Clothing Products
        $fashionProducts = [
            [
                'seller_id' => 2,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 2,
                'name' => 'Nike Air Max 270 Sneakers',
                'slug' => 'nike-air-max-270-sneakers',
                'description' => 'Comfortable and stylish Nike Air Max 270 sneakers with large Air unit and breathable mesh upper.',
                'b2c_price' => 149.99,
                'b2c_compare_price' => 179.99,
                'b2b_price' => 129.99,
                'b2b_moq' => 10,
                'stock_quantity' => 120,
                'category' => 'Shoes',
                'brand' => 'Nike',
                'model' => 'Air Max 270',
                'specifications' => ['size' => 'US 8-12', 'color' => 'Black/White', 'material' => 'Mesh/Synthetic', 'gender' => 'Unisex'],
                'images' => [
                    'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=500&auto=format&fit=crop'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.5,
                'verification_status' => 'approved',
                'category_id' => 4,
            ],
            [
                'seller_id' => 2,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 2,
                'name' => 'Levi\'s 501 Original Fit Jeans',
                'slug' => 'levis-501-original-fit-jeans',
                'description' => 'Classic Levi\'s 501 original fit jeans made from premium denim. Timeless style with button fly.',
                'b2c_price' => 89.99,
                'b2c_compare_price' => 109.99,
                'b2b_price' => 74.99,
                'b2b_moq' => 15,
                'stock_quantity' => 200,
                'category' => 'Clothing',
                'brand' => 'Levi\'s',
                'model' => '501 Original',
                'specifications' => ['size' => '28-38 waist', 'color' => 'Dark Blue', 'fit' => 'Original', 'material' => '100% Cotton'],
                'images' => [
                    'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1582552938357-32b906df40cb?w=500&auto=format&fit=crop'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.4,
                'verification_status' => 'approved',
                'category_id' => 5,
            ],
            [
                'seller_id' => 2,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 2,
                'name' => 'Ralph Lauren Polo Shirt',
                'slug' => 'ralph-lauren-polo-shirt',
                'description' => 'Classic Ralph Lauren polo shirt made from soft cotton mesh. Features the iconic polo player logo.',
                'b2c_price' => 79.99,
                'b2c_compare_price' => 95.99,
                'b2b_price' => 64.99,
                'b2b_moq' => 20,
                'stock_quantity' => 150,
                'category' => 'Clothing',
                'brand' => 'Ralph Lauren',
                'model' => 'Classic Polo',
                'specifications' => ['size' => 'S-XXL', 'color' => 'Navy Blue', 'material' => 'Cotton Mesh', 'fit' => 'Classic'],
                'images' => [
                    'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&auto=format&fit=crop',
                    'htgeom/p790170083-2f9ceadc732d?w=500&auto=format&fit=crop'
                ],
                'status' => 'active',
                'is_featured' => false,
                'rating' => 4.3,
                'verification_status' => 'approved',
                'category_id' => 5,
            ],
            [
                'seller_id' => 2,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 2,
                'name' => 'Ray-Ban Aviator Classic Sunglasses',
                'slug' => 'ray-ban-aviator-classic-sunglasses',
                'description' => 'Iconic Ray-Ban Aviator sunglasses with gold frame and green classic lenses. Timeless style and UV protection.',
                'b2c_price' => 154.99,
                'b2c_compare_price' => 179.99,
                'b2b_price' => 134.99,
                'b2b_moq' => 8,
                'stock_quantity' => 75,
                'category' => 'Accessories',
                'brand' => 'Ray-Ban',
                'model' => 'Aviator Classic',
                'specifications' => ['lens' => 'Green Classic', 'frame' => 'Gold', 'size' => '58mm', 'uv_protection' => '100%'],
                'images' => [
                    'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=500&auto=format&fit=crop'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.7,
                'verification_status' => 'approved',
                'category_id' => 6,
            ],
        ];

        // Watches & Jewelry Products
        $watchesProducts = [
            [
                'seller_id' => 3,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 3,
                'name' => 'Apple Watch Series 9 GPS 45mm',
                'slug' => 'apple-watch-series-9-gps-45mm',
                'description' => 'Latest Apple Watch Series 9 with S9 chip, double tap gesture, and advanced health monitoring features.',
                'b2c_price' => 429.99,
                'b2c_compare_price' => 479.99,
                'b2b_price' => 389.99,
                'b2b_moq' => 3,
                'stock_quantity' => 60,
                'category' => 'Smart Watches',
                'brand' => 'Apple',
                'model' => 'Watch Series 9',
                'specifications' => ['size' => '45mm', 'connectivity' => 'GPS', 'color' => 'Midnight', 'band' => 'Sport Band'],
                'images' => [
                    'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&auto=format&fit=crop'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.8,
                'verification_status' => 'approved',
                'category_id' => 7,
            ],
            [
                'seller_id' => 3,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 3,
                'name' => 'Rolex Submariner Date',
                'slug' => 'rolex-submariner-date',
                'description' => 'Luxury Rolex Submariner Date with Oystersteel case and bracelet. Water-resistant to 300 meters.',
                'b2c_price' => 8950.00,
                'b2c_compare_price' => 9500.00,
                'b2b_price' => 8500.00,
                'b2b_moq' => 1,
                'stock_quantity' => 5,
                'category' => 'Luxury Watches',
                'brand' => 'Rolex',
                'model' => 'Submariner Date',
                'specifications' => ['case' => 'Oystersteel', 'diameter' => '41mm', 'movement' => 'Automatic', 'water_resistance' => '300m'],
                'images' => [
                    'https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1609081219090-a6d81d3085bf?w=500&auto=format&fit=crop'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.9,
                'verification_status' => 'approved',
                'category_id' => 8,
            ],
            [
                'seller_id' => 3,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 3,
                'name' => 'Casio G-Shock GA-2100',
                'slug' => 'casio-g-shock-ga-2100',
                'description' => 'Rugged Casio G-Shock watch with carbon core guard structure. Shock resistant and water resistant.',
                'b2c_price' => 99.99,
                'b2c_compare_price' => 119.99,
                'b2b_price' => 84.99,
                'b2b_moq' => 12,
                'stock_quantity' => 100,
                'category' => 'Sports Watches',
                'brand' => 'Casio',
                'model' => 'G-Shock GA-2100',
                'specifications' => ['case' => 'Carbon', 'diameter' => '45mm', 'water_resistance' => '200m', 'battery' => '3 years'],
                'images' => [
                    'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1606859428306-b5cd5bb2ec9d?w=500&auto=format&fit=crop'
                ],
                'status' => 'active',
                'is_featured' => false,
                'rating' => 4.5,
                'verification_status' => 'approved',
                'category_id' => 9,
            ],
            [
                'seller_id' => 3,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 3,
                'name' => 'Tiffany & Co. Sterling Silver Necklace',
                'slug' => 'tiffany-co-sterling-silver-necklace',
                'description' => 'Elegant Tiffany & Co. sterling silver necklace with heart pendant. Perfect for special occasions.',
                'b2c_price' => 295.00,
                'b2c_compare_price' => 350.00,
                'b2b_price' => 265.00,
                'b2b_moq' => 5,
                'stock_quantity' => 30,
                'category' => 'Jewelry',
                'brand' => 'Tiffany & Co.',
                'model' => 'Heart Pendant',
                'specifications' => ['material' => 'Sterling Silver', 'pendant' => 'Heart', 'chain_length' => '16 inches', 'clasp' => 'Lobster'],
                'images' => [
                    'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?w=500&auto=format&fit=crop'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.6,
                'verification_status' => 'approved',
                'category_id' => 10,
            ],
        ];

        $products = [
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Jet Black Ink Cartridge',
                'slug' => 'jet-black-ink-cartridge',
                'description' => 'High quality black ink cartridge for Jet printers.',
                'b2c_price' => 19.99,
                'b2c_compare_price' => 24.99,
                'b2b_price' => 15.99,
                'b2b_moq' => 10,
                'stock_quantity' => 100,
                'category' => 'Ink Cartridges',
                'brand' => 'JetBrand',
                'model' => 'JB-1000',
                'specifications' => ['color' => 'Black', 'capacity' => '20ml'],
                'images' => [
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w-500&auto=format&fit=crop&crop=center'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.5,
                'verification_status' => 'approved',
                'category_id' => 1,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Color Ink Cartridge',
                'slug' => 'color-ink-cartridge',
                'description' => 'Vivid color ink cartridge for all major printers.',
                'b2c_price' => 22.99,
                'b2c_compare_price' => 27.99,
                'b2b_price' => 18.99,
                'b2b_moq' => 8,
                'stock_quantity' => 80,
                'category' => 'Ink Cartridges',
                'brand' => 'ColorJet',
                'model' => 'CJ-2000',
                'specifications' => ['color' => 'Tri-color', 'capacity' => '18ml'],
                'images' => [
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w-500&auto=format&fit=crop&crop=left'
                ],
                'status' => 'active',
                'is_featured' => false,
                'rating' => 4.2,
                'verification_status' => 'approved',
                'category_id' => 1,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Premium Photo Paper',
                'slug' => 'premium-photo-paper',
                'description' => 'Glossy photo paper for professional prints.',
                'b2c_price' => 12.99,
                'b2c_compare_price' => 15.99,
                'b2b_price' => 10.99,
                'b2b_moq' => 20,
                'stock_quantity' => 200,
                'category' => 'Paper',
                'brand' => 'PhotoPro',
                'model' => 'PP-300',
                'specifications' => ['size' => 'A4', 'finish' => 'Glossy'],
                'images' => [
                    'https://images.unsplash.com/photo-1509869175650-a1d97972541a?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1509869175650-a1d97972541a?w=500&auto=format&fit=crop&crop=right'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.8,
                'verification_status' => 'approved',
                'category_id' => 2,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Laser Toner Cartridge',
                'slug' => 'laser-toner-cartridge',
                'description' => 'High yield toner cartridge for laser printers.',
                'b2c_price' => 49.99,
                'b2c_compare_price' => 59.99,
                'b2b_price' => 39.99,
                'b2b_moq' => 5,
                'stock_quantity' => 60,
                'category' => 'Toner Cartridges',
                'brand' => 'LaserMax',
                'model' => 'LM-500',
                'specifications' => ['color' => 'Black', 'yield' => '3000 pages'],
                'images' => [
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&crop=top'
                ],
                'status' => 'active',
                'is_featured' => false,
                'rating' => 4.6,
                'verification_status' => 'approved',
                'category_id' => 3,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Matte Photo Paper',
                'slug' => 'matte-photo-paper',
                'description' => 'Matte finish photo paper for everyday use.',
                'b2c_price' => 10.99,
                'b2c_compare_price' => 13.99,
                'b2b_price' => 8.99,
                'b2b_moq' => 25,
                'stock_quantity' => 150,
                'category' => 'Paper',
                'brand' => 'PrintEase',
                'model' => 'PE-400',
                'specifications' => ['size' => 'A4', 'finish' => 'Matte'],
                'images' => [
                    'https://images.unsplash.com/photo-1509869175650-a1d97972541a?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1509869175650-a1d97972541a?w=500&auto=format&fit=crop&crop=bottom'
                ],
                'status' => 'active',
                'is_featured' => false,
                'rating' => 4.1,
                'verification_status' => 'approved',
                'category_id' => 2,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Eco-Friendly Ink Cartridge',
                'slug' => 'eco-friendly-ink-cartridge',
                'description' => 'Environmentally friendly ink cartridge.',
                'b2c_price' => 21.99,
                'b2c_compare_price' => 26.99,
                'b2b_price' => 17.99,
                'b2b_moq' => 12,
                'stock_quantity' => 90,
                'category' => 'Ink Cartridges',
                'brand' => 'EcoPrint',
                'model' => 'EP-1100',
                'specifications' => ['color' => 'Black', 'eco' => true],
                'images' => [
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&crop=entropy'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.7,
                'verification_status' => 'approved',
                'category_id' => 1,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Professional Matte Paper - A3',
                'slug' => 'professional-matte-paper-a3',
                'description' => 'A3 size matte paper for professional documents.',
                'b2c_price' => 18.99,
                'b2c_compare_price' => 22.99,
                'b2b_price' => 15.99,
                'b2b_moq' => 15,
                'stock_quantity' => 120,
                'category' => 'Paper',
                'brand' => 'DocPro',
                'model' => 'DP-A3-200',
                'specifications' => ['size' => 'A3', 'weight' => '120gsm', 'finish' => 'Matte'],
                'images' => [
                    'https://images.unsplash.com/photo-1509869175650-a1d97972541a?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1509869175650-a1d97972541a?w=500&auto=format&fit=crop&crop=focalpoint'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.4,
                'verification_status' => 'approved',
                'category_id' => 2,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Color Laser Toner',
                'slug' => 'color-laser-toner',
                'description' => 'Full color toner set for color laser printers.',
                'b2c_price' => 89.99,
                'b2c_compare_price' => 109.99,
                'b2b_price' => 74.99,
                'b2b_moq' => 4,
                'stock_quantity' => 45,
                'category' => 'Toner Cartridges',
                'brand' => 'ColorMax',
                'model' => 'CM-800',
                'specifications' => ['colors' => 'CMYK', 'yield' => '2500 pages'],
                'images' => [
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&crop=edges'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.9,
                'verification_status' => 'approved',
                'category_id' => 3,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'XL High Capacity Ink',
                'slug' => 'xl-high-capacity-ink',
                'description' => 'Extra large capacity ink cartridge for heavy printing.',
                'b2c_price' => 34.99,
                'b2c_compare_price' => 39.99,
                'b2b_price' => 28.99,
                'b2b_moq' => 6,
                'stock_quantity' => 75,
                'category' => 'Ink Cartridges',
                'brand' => 'MegaInk',
                'model' => 'MI-XL500',
                'specifications' => ['color' => 'Black', 'capacity' => '50ml'],
                'images' => [
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&crop=faces'
                ],
                'status' => 'active',
                'is_featured' => false,
                'rating' => 4.3,
                'verification_status' => 'pending',
                'category_id' => 1,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 2,
                'name' => 'Recycled Office Paper',
                'slug' => 'recycled-office-paper',
                'description' => 'Eco-friendly recycled paper for everyday office use.',
                'b2c_price' => 8.99,
                'b2c_compare_price' => 11.99,
                'b2b_price' => 6.99,
                'b2b_moq' => 30,
                'stock_quantity' => 300,
                'category' => 'Paper',
                'brand' => 'EcoOffice',
                'model' => 'EO-100',
                'specifications' => ['size' => 'A4', 'recycled' => true, 'weight' => '80gsm'],
                'images' => [
                    'https://images.unsplash.com/photo-1509869175650-a1d97972541a?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1509869175650-a1d97972541a?w=500&auto=format&fit=crop&crop=center'
                ],
                'status' => 'active',
                'is_featured' => false,
                'rating' => 4.0,
                'verification_status' => 'approved',
                'category_id' => 2,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\null',
                'owner_id' => 2,
                'name' => 'Premium Photo Glossy Paper - A4',
                'slug' => 'premium-photo-glossy-paper-a4',
                'description' => 'Professional grade glossy photo paper for high-quality prints.',
                'b2c_price' => 24.99,
                'b2c_compare_price' => 29.99,
                'b2b_price' => 19.99,
                'b2b_moq' => 10,
                'stock_quantity' => 100,
                'category' => 'Paper',
                'brand' => 'PhotoElite',
                'model' => 'PE-GLOSS-300',
                'specifications' => ['size' => 'A4', 'finish' => 'High Gloss', 'weight' => '200gsm'],
                'images' => [
                    'https://images.unsplash.com/photo-1509869175650-a1d97972541a?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1509869175650-a1d97972541a?w=500&auto=format&fit=crop&crop=left'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.8,
                'verification_status' => 'approved',
                'category_id' => 2,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 2,
                'name' => 'Compact Ink Cartridge Set',
                'slug' => 'compact-ink-cartridge-set',
                'description' => 'Complete ink set for compact printers.',
                'b2c_price' => 29.99,
                'b2c_compare_price' => 35.99,
                'b2b_price' => 24.99,
                'b2b_moq' => 8,
                'stock_quantity' => 110,
                'category' => 'Ink Cartridges',
                'brand' => 'CompactPrint',
                'model' => 'CP-250',
                'specifications' => ['colors' => 'Black + Color', 'capacity' => '15ml each'],
                'images' => [
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&crop=right'
                ],
                'status' => 'active',
                'is_featured' => false,
                'rating' => 4.2,
                'verification_status' => 'approved',
                'category_id' => 1,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'High-Yield Laser Toner',
                'slug' => 'high-yield-laser-toner',
                'description' => 'Ultra high yield toner for office laser printers.',
                'b2c_price' => 69.99,
                'b2c_compare_price' => 79.99,
                'b2b_price' => 59.99,
                'b2b_moq' => 4,
                'stock_quantity' => 50,
                'category' => 'Toner Cartridges',
                'brand' => 'OfficeMax',
                'model' => 'OM-1200',
                'specifications' => ['color' => 'Black', 'yield' => '5000 pages'],
                'images' => [
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&crop=top'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.7,
                'verification_status' => 'approved',
                'category_id' => 3,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Archival Matte Paper',
                'slug' => 'archival-matte-paper',
                'description' => 'Acid-free archival paper for long-lasting prints.',
                'b2c_price' => 32.99,
                'b2c_compare_price' => 39.99,
                'b2b_price' => 26.99,
                'b2b_moq' => 8,
                'stock_quantity' => 85,
                'category' => 'Paper',
                'brand' => 'ArchivePro',
                'model' => 'AP-1000',
                'specifications' => ['size' => 'A4', 'acid-free' => true, 'weight' => '180gsm'],
                'images' => [
                    'https://images.unsplash.com/photo-1509869175650-a1d97972541a?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1509869175650-a1d97972541a?w=500&auto=format&fit=crop&crop=bottom'
                ],
                'status' => 'active',
                'is_featured' => false,
                'rating' => 4.6,
                'verification_status' => 'approved',
                'category_id' => 2,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 2,
                'name' => 'Refillable Ink Tank System',
                'slug' => 'refillable-ink-tank-system',
                'description' => 'Eco-friendly refillable ink tank system.',
                'b2c_price' => 44.99,
                'b2c_compare_price' => 54.99,
                'b2b_price' => 37.99,
                'b2b_moq' => 5,
                'stock_quantity' => 65,
                'category' => 'Ink Cartridges',
                'brand' => 'EcoTank',
                'model' => 'ET-2000',
                'specifications' => ['refillable' => true, 'capacity' => '100ml'],
                'images' => [
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&crop=entropy'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.9,
                'verification_status' => 'approved',
                'category_id' => 1,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Multi-Purpose Paper Bundle',
                'slug' => 'multi-purpose-paper-bundle',
                'description' => '5 ream bundle of multi-purpose office paper.',
                'b2c_price' => 39.99,
                'b2c_compare_price' => 49.99,
                'b2b_price' => 32.99,
                'b2b_moq' => 3,
                'stock_quantity' => 40,
                'category' => 'Paper',
                'brand' => 'OfficeBundle',
                'model' => 'OB-5PK',
                'specifications' => ['reams' => 5, 'sheets_per_ream' => 500, 'weight' => '80gsm'],
                'images' => [
                    'https://images.unsplash.com/photo-1509869175650-a1d97972541a?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1509869175650-a1d97972541a?w=500&auto=format&fit=crop&crop=focalpoint'
                ],
                'status' => 'active',
                'is_featured' => false,
                'rating' => 4.3,
                'verification_status' => 'approved',
                'category_id' => 2,
            ],
        ];

        // Professional Products for Seller ID 4
        $seller4Products = [
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'HP LaserJet Pro M404dn Monochrome Printer',
                'slug' => 'hp-laserjet-pro-m404dn-monochrome-printer',
                'description' => 'Professional monochrome laser printer with duplex printing and network connectivity. Perfect for small to medium offices.',
                'b2c_price' => 299.99,
                'b2c_compare_price' => 349.99,
                'b2b_price' => 249.99,
                'b2b_moq' => 2,
                'stock_quantity' => 25,
                'category' => 'Printers',
                'brand' => 'HP',
                'model' => 'M404dn',
                'specifications' => ['type' => 'Laser', 'color' => 'Monochrome', 'duplex' => true, 'network' => true, 'speed' => '38 ppm'],
                'images' => [
                    'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=500&auto=format&fit=crop&crop=center'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.7,
                'verification_status' => 'approved',
                'category_id' => 4,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Canon PIXMA TR8620 All-in-One Wireless Printer',
                'slug' => 'canon-pixma-tr8620-all-in-one-wireless-printer',
                'description' => 'Versatile all-in-one printer with wireless connectivity, automatic document feeder, and high-quality photo printing.',
                'b2c_price' => 199.99,
                'b2c_compare_price' => 249.99,
                'b2b_price' => 169.99,
                'b2b_moq' => 3,
                'stock_quantity' => 30,
                'category' => 'Printers',
                'brand' => 'Canon',
                'model' => 'PIXMA TR8620',
                'specifications' => ['type' => 'Inkjet', 'color' => 'Color', 'wireless' => true, 'adf' => true, 'functions' => 'Print/Scan/Copy/Fax'],
                'images' => [
                    'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=500&auto=format&fit=crop&crop=left'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.5,
                'verification_status' => 'approved',
                'category_id' => 4,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'HP 58A Black Original LaserJet Toner Cartridge',
                'slug' => 'hp-58a-black-original-laserjet-toner-cartridge',
                'description' => 'Genuine HP 58A black toner cartridge delivering professional quality prints with consistent performance.',
                'b2c_price' => 89.99,
                'b2c_compare_price' => 109.99,
                'b2b_price' => 74.99,
                'b2b_moq' => 5,
                'stock_quantity' => 150,
                'category' => 'Toner Cartridges',
                'brand' => 'HP',
                'model' => '58A (CF258A)',
                'specifications' => ['color' => 'Black', 'yield' => '3000 pages', 'compatibility' => 'HP LaserJet Pro M404/M428 series'],
                'images' => [
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&crop=right'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.8,
                'verification_status' => 'approved',
                'category_id' => 2,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Canon PGI-280XL/CLI-281XL High Yield Ink Cartridge Set',
                'slug' => 'canon-pgi-280xl-cli-281xl-high-yield-ink-cartridge-set',
                'description' => 'Complete set of high-yield ink cartridges for Canon PIXMA printers. Includes black and color cartridges.',
                'b2c_price' => 129.99,
                'b2c_compare_price' => 159.99,
                'b2b_price' => 109.99,
                'b2b_moq' => 4,
                'stock_quantity' => 80,
                'category' => 'Ink Cartridges',
                'brand' => 'Canon',
                'model' => 'PGI-280XL/CLI-281XL',
                'specifications' => ['colors' => 'Black, Cyan, Magenta, Yellow', 'yield' => 'XL capacity', 'compatibility' => 'Canon PIXMA TR7520/TR8520/TS6120/TS8120'],
                'images' => [
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&crop=top'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.6,
                'verification_status' => 'approved',
                'category_id' => 1,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Hammermill Premium Laser Print Paper 24lb',
                'slug' => 'hammermill-premium-laser-print-paper-24lb',
                'description' => 'Premium 24lb laser paper for professional documents. Acid-free and jam-free guaranteed performance.',
                'b2c_price' => 45.99,
                'b2c_compare_price' => 54.99,
                'b2b_price' => 38.99,
                'b2b_moq' => 10,
                'stock_quantity' => 200,
                'category' => 'Paper',
                'brand' => 'Hammermill',
                'model' => 'Premium Laser 24lb',
                'specifications' => ['weight' => '24lb (90gsm)', 'size' => '8.5x11', 'sheets' => '500 per ream', 'brightness' => '98'],
                'images' => [
                    'https://images.unsplash.com/photo-1509869175650-a1d97972541a?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1509869175650-a1d97972541a?w=500&auto=format&fit=crop&crop=bottom'
                ],
                'status' => 'active',
                'is_featured' => false,
                'rating' => 4.4,
                'verification_status' => 'approved',
                'category_id' => 3,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'HP Advanced Photo Paper Glossy 4x6',
                'slug' => 'hp-advanced-photo-paper-glossy-4x6',
                'description' => 'Professional glossy photo paper for vibrant, lab-quality photos. Instant dry technology.',
                'b2c_price' => 19.99,
                'b2c_compare_price' => 24.99,
                'b2b_price' => 16.99,
                'b2b_moq' => 20,
                'stock_quantity' => 300,
                'category' => 'Specialty Papers',
                'brand' => 'HP',
                'model' => 'Advanced Photo Paper',
                'specifications' => ['size' => '4x6 inches', 'finish' => 'Glossy', 'weight' => '250gsm', 'sheets' => '100 per pack'],
                'images' => [
                    'https://images.unsplash.com/photo-1509869175650-a1d97972541a?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1509869175650-a1d97972541a?w=500&auto=format&fit=crop&crop=entropy'
                ],
                'status' => 'active',
                'is_featured' => false,
                'rating' => 4.7,
                'verification_status' => 'approved',
                'category_id' => 8,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Brother TN760 High Yield Black Toner Cartridge',
                'slug' => 'brother-tn760-high-yield-black-toner-cartridge',
                'description' => 'High-yield black toner cartridge for Brother laser printers. Delivers sharp, professional text.',
                'b2c_price' => 79.99,
                'b2c_compare_price' => 99.99,
                'b2b_price' => 67.99,
                'b2b_moq' => 6,
                'stock_quantity' => 120,
                'category' => 'Toner Cartridges',
                'brand' => 'Brother',
                'model' => 'TN760',
                'specifications' => ['color' => 'Black', 'yield' => '3000 pages', 'compatibility' => 'Brother HL-L2350DW/L2370DW/L2390DW/L2395DW'],
                'images' => [
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&crop=focalpoint'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.5,
                'verification_status' => 'approved',
                'category_id' => 2,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Epson EcoTank ET-2720 Wireless All-in-One Printer',
                'slug' => 'epson-ecotank-et-2720-wireless-all-in-one-printer',
                'description' => 'Cartridge-free printing with easy-to-fill supersized ink tanks. Includes up to 2 years of ink in the box.',
                'b2c_price' => 249.99,
                'b2c_compare_price' => 299.99,
                'b2b_price' => 219.99,
                'b2b_moq' => 2,
                'stock_quantity' => 20,
                'category' => 'Printers',
                'brand' => 'Epson',
                'model' => 'EcoTank ET-2720',
                'specifications' => ['type' => 'Inkjet', 'color' => 'Color', 'wireless' => true, 'tank_system' => true, 'functions' => 'Print/Scan/Copy'],
                'images' => [
                    'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=500&auto=format&fit=crop&crop=edges'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.3,
                'verification_status' => 'approved',
                'category_id' => 4,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'HP 962XL High Yield Ink Cartridge Combo Pack',
                'slug' => 'hp-962xl-high-yield-ink-cartridge-combo-pack',
                'description' => 'Complete combo pack of HP 962XL high-yield ink cartridges for HP OfficeJet Pro 9010/9020 series.',
                'b2c_price' => 149.99,
                'b2c_compare_price' => 179.99,
                'b2b_price' => 127.99,
                'b2b_moq' => 3,
                'stock_quantity' => 90,
                'category' => 'Ink Cartridges',
                'brand' => 'HP',
                'model' => '962XL Combo',
                'specifications' => ['colors' => 'Black, Cyan, Magenta, Yellow', 'yield' => 'XL capacity', 'compatibility' => 'HP OfficeJet Pro 9010/9020 series'],
                'images' => [
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&crop=faces'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.6,
                'verification_status' => 'approved',
                'category_id' => 1,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Avery Address Labels for Laser Printers',
                'slug' => 'avery-address-labels-for-laser-printers',
                'description' => 'Professional address labels compatible with laser printers. Easy peel technology and jam-free guarantee.',
                'b2c_price' => 24.99,
                'b2c_compare_price' => 29.99,
                'b2b_price' => 21.99,
                'b2b_moq' => 15,
                'stock_quantity' => 250,
                'category' => 'Labels & Stickers',
                'brand' => 'Avery',
                'model' => '5160',
                'specifications' => ['size' => '1" x 2-5/8"', 'labels_per_sheet' => 30, 'sheets_per_box' => 100, 'total_labels' => 3000],
                'images' => [
                    'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=500&auto=format&fit=crop&crop=center'
                ],
                'status' => 'active',
                'is_featured' => false,
                'rating' => 4.4,
                'verification_status' => 'approved',
                'category_id' => 10,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Lexmark B2236dw Monochrome Laser Printer',
                'slug' => 'lexmark-b2236dw-monochrome-laser-printer',
                'description' => 'Compact monochrome laser printer with wireless connectivity and automatic duplex printing.',
                'b2c_price' => 179.99,
                'b2c_compare_price' => 219.99,
                'b2b_price' => 154.99,
                'b2b_moq' => 3,
                'stock_quantity' => 35,
                'category' => 'Printers',
                'brand' => 'Lexmark',
                'model' => 'B2236dw',
                'specifications' => ['type' => 'Laser', 'color' => 'Monochrome', 'wireless' => true, 'duplex' => true, 'speed' => '34 ppm'],
                'images' => [
                    'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=500&auto=format&fit=crop&crop=left'
                ],
                'status' => 'active',
                'is_featured' => false,
                'rating' => 4.2,
                'verification_status' => 'approved',
                'category_id' => 4,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'HP Printer Maintenance Kit for LaserJet Pro',
                'slug' => 'hp-printer-maintenance-kit-for-laserjet-pro',
                'description' => 'Complete maintenance kit for HP LaserJet Pro printers. Includes fuser, rollers, and cleaning supplies.',
                'b2c_price' => 189.99,
                'b2c_compare_price' => 229.99,
                'b2b_price' => 164.99,
                'b2b_moq' => 2,
                'stock_quantity' => 40,
                'category' => 'Maintenance Kits',
                'brand' => 'HP',
                'model' => 'LaserJet Pro Maintenance Kit',
                'specifications' => ['includes' => 'Fuser, Transfer Roller, Pickup Rollers', 'compatibility' => 'HP LaserJet Pro M404/M428 series', 'yield' => '100000 pages'],
                'images' => [
                    'https://images.unsplash.com/photo-1572025443061-3f53d8b8a2ec?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1572025443061-3f53d8b8a2ec?w=500&auto=format&fit=crop&crop=right'
                ],
                'status' => 'active',
                'is_featured' => false,
                'rating' => 4.7,
                'verification_status' => 'approved',
                'category_id' => 7,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Staples Copy Paper 20lb Multipurpose',
                'slug' => 'staples-copy-paper-20lb-multipurpose',
                'description' => 'Everyday multipurpose copy paper for all office needs. 99.99% jam-free guarantee.',
                'b2c_price' => 29.99,
                'b2c_compare_price' => 34.99,
                'b2b_price' => 25.99,
                'b2b_moq' => 20,
                'stock_quantity' => 500,
                'category' => 'Office Supplies',
                'brand' => 'Staples',
                'model' => 'Multipurpose 20lb',
                'specifications' => ['weight' => '20lb (75gsm)', 'size' => '8.5x11', 'sheets' => '500 per ream', 'brightness' => '92'],
                'images' => [
                    'https://images.unsplash.com/photo-1509869175650-a1d97972541a?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1509869175650-a1d97972541a?w=500&auto=format&fit=crop&crop=top'
                ],
                'status' => 'active',
                'is_featured' => false,
                'rating' => 4.1,
                'verification_status' => 'approved',
                'category_id' => 6,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Canon Pro Platinum Photo Paper 13x19',
                'slug' => 'canon-pro-platinum-photo-paper-13x19',
                'description' => 'Professional platinum photo paper for gallery-quality prints. Instant dry and water resistant.',
                'b2c_price' => 89.99,
                'b2c_compare_price' => 109.99,
                'b2b_price' => 76.99,
                'b2b_moq' => 5,
                'stock_quantity' => 60,
                'category' => 'Specialty Papers',
                'brand' => 'Canon',
                'model' => 'Pro Platinum',
                'specifications' => ['size' => '13x19 inches', 'finish' => 'Glossy', 'weight' => '300gsm', 'sheets' => '20 per pack'],
                'images' => [
                    'https://images.unsplash.com/photo-1509869175650-a1d97972541a?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1509869175650-a1d97972541a?w=500&auto=format&fit=crop&crop=bottom'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.9,
                'verification_status' => 'approved',
                'category_id' => 8,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Zebra ZP 450 Thermal Label Printer',
                'slug' => 'zebra-zp-450-thermal-label-printer',
                'description' => 'Direct thermal label printer perfect for shipping labels, barcodes, and inventory management.',
                'b2c_price' => 199.99,
                'b2c_compare_price' => 249.99,
                'b2b_price' => 174.99,
                'b2b_moq' => 2,
                'stock_quantity' => 25,
                'category' => 'Printers',
                'brand' => 'Zebra',
                'model' => 'ZP 450',
                'specifications' => ['type' => 'Thermal', 'max_width' => '4.09 inches', 'resolution' => '203 dpi', 'connectivity' => 'USB'],
                'images' => [
                    'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=500&auto=format&fit=crop&crop=entropy'
                ],
                'status' => 'active',
                'is_featured' => false,
                'rating' => 4.5,
                'verification_status' => 'approved',
                'category_id' => 4,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Epson Ribbon Cartridge for Dot Matrix Printers',
                'slug' => 'epson-ribbon-cartridge-for-dot-matrix-printers',
                'description' => 'High-quality ribbon cartridge for Epson dot matrix printers. Long-lasting and reliable performance.',
                'b2c_price' => 15.99,
                'b2c_compare_price' => 19.99,
                'b2b_price' => 13.99,
                'b2b_moq' => 25,
                'stock_quantity' => 180,
                'category' => 'Ribbons',
                'brand' => 'Epson',
                'model' => 'S015327',
                'specifications' => ['color' => 'Black', 'compatibility' => 'Epson LX-300/LX-300+/LX-300+II', 'yield' => '4 million characters'],
                'images' => [
                    'https://images.unsplash.com/photo-1572025443061-3f53d8b8a2ec?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1572025443061-3f53d8b8a2ec?w=500&auto=format&fit=crop&crop=focalpoint'
                ],
                'status' => 'active',
                'is_featured' => false,
                'rating' => 4.3,
                'verification_status' => 'approved',
                'category_id' => 9,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Brother LC3013 Super High Yield Ink Cartridge Set',
                'slug' => 'brother-lc3013-super-high-yield-ink-cartridge-set',
                'description' => 'Super high yield ink cartridge set for Brother MFC-J491DW/J497DW/J690DW/J895DW printers.',
                'b2c_price' => 99.99,
                'b2c_compare_price' => 119.99,
                'b2b_price' => 84.99,
                'b2b_moq' => 4,
                'stock_quantity' => 70,
                'category' => 'Ink Cartridges',
                'brand' => 'Brother',
                'model' => 'LC3013',
                'specifications' => ['colors' => 'Black, Cyan, Magenta, Yellow', 'yield' => 'Super High Yield', 'compatibility' => 'Brother MFC-J491DW/J497DW/J690DW/J895DW'],
                'images' => [
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=500&auto=format&fit=crop&crop=edges'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.4,
                'verification_status' => 'approved',
                'category_id' => 1,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'HP Smart Tank Plus 651 Wireless All-in-One Printer',
                'slug' => 'hp-smart-tank-plus-651-wireless-all-in-one-printer',
                'description' => 'Smart tank printer with up to 3 years of ink included. Wireless connectivity and mobile printing.',
                'b2c_price' => 279.99,
                'b2c_compare_price' => 329.99,
                'b2b_price' => 244.99,
                'b2b_moq' => 2,
                'stock_quantity' => 18,
                'category' => 'Printers',
                'brand' => 'HP',
                'model' => 'Smart Tank Plus 651',
                'specifications' => ['type' => 'Inkjet', 'color' => 'Color', 'wireless' => true, 'tank_system' => true, 'functions' => 'Print/Scan/Copy/Fax'],
                'images' => [
                    'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=500&auto=format&fit=crop&crop=faces'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.6,
                'verification_status' => 'approved',
                'category_id' => 4,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Scotch Thermal Laminating Pouches Letter Size',
                'slug' => 'scotch-thermal-laminating-pouches-letter-size',
                'description' => 'Professional thermal laminating pouches for document protection. Crystal clear finish.',
                'b2c_price' => 34.99,
                'b2c_compare_price' => 42.99,
                'b2b_price' => 29.99,
                'b2b_moq' => 10,
                'stock_quantity' => 150,
                'category' => 'Office Supplies',
                'brand' => 'Scotch',
                'model' => 'TP3854-100',
                'specifications' => ['size' => '8.5x11 inches', 'thickness' => '5 mil', 'pouches' => '100 per pack', 'finish' => 'Clear'],
                'images' => [
                    'https://images.unsplash.com/photo-1572025443061-3f53d8b8a2ec?w=500&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1572025443061-3f53d8b8a2ec?w=500&auto=format&fit=crop&crop=center'
                ],
                'status' => 'active',
                'is_featured' => false,
                'rating' => 4.2,
                'verification_status' => 'approved',
                'category_id' => 6,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }

        foreach ($seller4Products as $product) {
            Product::create($product);
        }
    }
}