<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            // Clothing Products
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Premium Cotton T-Shirt',
                'slug' => 'premium-cotton-t-shirt',
                'description' => 'Soft, breathable 100% cotton t-shirt available in various colors. Perfect for casual wear.',
                'b2c_price' => 24.99,
                'b2c_compare_price' => 34.99,
                'b2b_price' => 18.99,
                'b2b_moq' => 12,
                'stock_quantity' => 150,
                'category' => 'Clothing',
                'brand' => 'UrbanWear',
                'model' => 'UTS-101',
                'specifications' => ['material' => '100% Cotton', 'size' => 'S-XXL', 'colors' => 'White, Black, Blue, Gray'],
                'images' => [
                    'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&auto=format&fit=crop&crop=top'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.5,
                'verification_status' => 'approved',
                'category_id' => 5, // Assuming 5 is for Clothing
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Classic Denim Jeans',
                'slug' => 'classic-denim-jeans',
                'description' => 'Durable denim jeans with modern fit. Available in various washes and sizes.',
                'b2c_price' => 59.99,
                'b2c_compare_price' => 79.99,
                'b2b_price' => 45.99,
                'b2b_moq' => 8,
                'stock_quantity' => 100,
                'category' => 'Clothing',
                'brand' => 'DenimCo',
                'model' => 'DJ-202',
                'specifications' => ['material' => '98% Cotton, 2% Elastane', 'fit' => 'Slim', 'wash' => 'Dark Blue, Light Blue, Black'],
                'images' => [
                    'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&auto=format&fit=crop&crop=right'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.7,
                'verification_status' => 'approved',
                'category_id' => 5,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Winter Jacket with Hood',
                'slug' => 'winter-jacket-with-hood',
                'description' => 'Water-resistant winter jacket with insulated lining and detachable hood.',
                'b2c_price' => 129.99,
                'b2c_compare_price' => 169.99,
                'b2b_price' => 99.99,
                'b2b_moq' => 5,
                'stock_quantity' => 75,
                'category' => 'Clothing',
                'brand' => 'OutdoorGear',
                'model' => 'WJ-305',
                'specifications' => ['material' => 'Polyester, Water-resistant', 'insulation' => 'Thermal', 'features' => 'Detachable Hood, Multiple Pockets'],
                'images' => [
                    'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&auto=format&fit=crop&crop=left'
                ],
                'status' => 'active',
                'is_featured' => false,
                'rating' => 4.6,
                'verification_status' => 'approved',
                'category_id' => 5,
            ],

            // Mobile Phones
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Smartphone Pro Max 128GB',
                'slug' => 'smartphone-pro-max-128gb',
                'description' => 'Latest smartphone with 6.7" display, triple camera, and 128GB storage.',
                'b2c_price' => 899.99,
                'b2c_compare_price' => 999.99,
                'b2b_price' => 799.99,
                'b2b_moq' => 3,
                'stock_quantity' => 50,
                'category' => 'Mobile Phones',
                'brand' => 'PhoneX',
                'model' => 'Pro Max 128GB',
                'specifications' => ['display' => '6.7" OLED', 'storage' => '128GB', 'camera' => 'Triple 48MP', 'battery' => '4500mAh'],
                'images' => [
                    'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&auto=format&fit=crop&crop=top'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.8,
                'verification_status' => 'approved',
                'category_id' => 6, // Assuming 6 is for Mobile Phones
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Budget Smartphone 64GB',
                'slug' => 'budget-smartphone-64gb',
                'description' => 'Affordable smartphone with decent performance and good battery life.',
                'b2c_price' => 299.99,
                'b2c_compare_price' => 349.99,
                'b2b_price' => 249.99,
                'b2b_moq' => 10,
                'stock_quantity' => 200,
                'category' => 'Mobile Phones',
                'brand' => 'MobilePlus',
                'model' => 'BP-64',
                'specifications' => ['display' => '6.5" LCD', 'storage' => '64GB', 'camera' => 'Dual 16MP', 'battery' => '5000mAh'],
                'images' => [
                    'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=600&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1565849904461-04a58ad377e0?w=600&auto=format&fit=crop&crop=right'
                ],
                'status' => 'active',
                'is_featured' => false,
                'rating' => 4.2,
                'verification_status' => 'approved',
                'category_id' => 6,
            ],

            // Accessories
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Leather Messenger Bag',
                'slug' => 'leather-messenger-bag',
                'description' => 'Genuine leather messenger bag with multiple compartments for daily use.',
                'b2c_price' => 89.99,
                'b2c_compare_price' => 119.99,
                'b2b_price' => 69.99,
                'b2b_moq' => 6,
                'stock_quantity' => 80,
                'category' => 'Accessories',
                'brand' => 'LeatherCraft',
                'model' => 'MB-501',
                'specifications' => ['material' => 'Genuine Leather', 'size' => '15.6" Laptop', 'color' => 'Brown, Black'],
                'images' => [
                    'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&crop=left'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.7,
                'verification_status' => 'approved',
                'category_id' => 7, // Assuming 7 is for Accessories
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Sunglasses UV Protection',
                'slug' => 'sunglasses-uv-protection',
                'description' => 'Polarized sunglasses with 100% UV protection and stylish design.',
                'b2c_price' => 39.99,
                'b2c_compare_price' => 59.99,
                'b2b_price' => 29.99,
                'b2b_moq' => 15,
                'stock_quantity' => 120,
                'category' => 'Accessories',
                'brand' => 'SunStyle',
                'model' => 'SS-401',
                'specifications' => ['lens' => 'Polarized', 'UV protection' => '100%', 'frame' => 'Acetate', 'colors' => 'Black, Brown, Tortoise'],
                'images' => [
                    'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&auto=format&fit=crop&crop=top'
                ],
                'status' => 'active',
                'is_featured' => false,
                'rating' => 4.4,
                'verification_status' => 'approved',
                'category_id' => 7,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Premium Wrist Watch',
                'slug' => 'premium-wrist-watch',
                'description' => 'Elegant wrist watch with stainless steel case and leather strap.',
                'b2c_price' => 159.99,
                'b2c_compare_price' => 199.99,
                'b2b_price' => 129.99,
                'b2b_moq' => 5,
                'stock_quantity' => 60,
                'category' => 'Watches',
                'brand' => 'TimeMaster',
                'model' => 'WM-701',
                'specifications' => ['movement' => 'Quartz', 'case' => 'Stainless Steel', 'strap' => 'Genuine Leather', 'water_resistant' => '50m'],
                'images' => [
                    'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=600&auto=format&fit=crop&crop=right'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.9,
                'verification_status' => 'approved',
                'category_id' => 8, // Assuming 8 is for Watches
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Smart Fitness Watch',
                'slug' => 'smart-fitness-watch',
                'description' => 'Advanced smartwatch with heart rate monitoring, GPS, and fitness tracking.',
                'b2c_price' => 249.99,
                'b2c_compare_price' => 299.99,
                'b2b_price' => 199.99,
                'b2b_moq' => 4,
                'stock_quantity' => 90,
                'category' => 'Watches',
                'brand' => 'FitTech',
                'model' => 'SFW-901',
                'specifications' => ['display' => 'AMOLED', 'battery' => '7 days', 'features' => 'GPS, Heart Rate, Sleep Tracking', 'water_resistant' => '5ATM'],
                'images' => [
                    'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=600&auto=format&fit=crop&crop=left'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.6,
                'verification_status' => 'approved',
                'category_id' => 8,
            ],

            // Electronics
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Wireless Bluetooth Earbuds',
                'slug' => 'wireless-bluetooth-earbuds',
                'description' => 'True wireless earbuds with noise cancellation and 30-hour battery life.',
                'b2c_price' => 79.99,
                'b2c_compare_price' => 99.99,
                'b2b_price' => 64.99,
                'b2b_moq' => 8,
                'stock_quantity' => 150,
                'category' => 'Electronics',
                'brand' => 'SoundWave',
                'model' => 'SWB-301',
                'specifications' => ['battery' => '30 hours', 'connectivity' => 'Bluetooth 5.2', 'features' => 'Noise Cancellation, Water Resistant'],
                'images' => [
                    'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&crop=top'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.5,
                'verification_status' => 'approved',
                'category_id' => 9, // Assuming 9 is for Electronics
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Laptop 15" 512GB SSD',
                'slug' => 'laptop-15-512gb-ssd',
                'description' => 'Powerful laptop with 15" display, 16GB RAM, and 512GB SSD for productivity.',
                'b2c_price' => 899.99,
                'b2c_compare_price' => 1099.99,
                'b2b_price' => 799.99,
                'b2b_moq' => 3,
                'stock_quantity' => 40,
                'category' => 'Electronics',
                'brand' => 'TechPro',
                'model' => 'LP-15512',
                'specifications' => ['display' => '15.6" FHD', 'ram' => '16GB', 'storage' => '512GB SSD', 'processor' => 'Intel i7'],
                'images' => [
                    'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&auto=format&fit=crop&crop=right'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.7,
                'verification_status' => 'approved',
                'category_id' => 9,
            ],

            // Home & Kitchen
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Stainless Steel Cookware Set',
                'slug' => 'stainless-steel-cookware-set',
                'description' => '10-piece stainless steel cookware set with non-stick coating.',
                'b2c_price' => 149.99,
                'b2c_compare_price' => 199.99,
                'b2b_price' => 119.99,
                'b2b_moq' => 4,
                'stock_quantity' => 60,
                'category' => 'Home & Kitchen',
                'brand' => 'KitchenPro',
                'model' => 'KP-1001',
                'specifications' => ['material' => 'Stainless Steel', 'pieces' => '10', 'features' => 'Non-stick, Dishwasher Safe'],
                'images' => [
                    'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&auto=format&fit=crop&crop=left'
                ],
                'status' => 'active',
                'is_featured' => false,
                'rating' => 4.4,
                'verification_status' => 'approved',
                'category_id' => 10, // Assuming 10 is for Home & Kitchen
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Smart Coffee Maker',
                'slug' => 'smart-coffee-maker',
                'description' => 'Programmable coffee maker with smartphone control and thermal carafe.',
                'b2c_price' => 89.99,
                'b2c_compare_price' => 129.99,
                'b2b_price' => 74.99,
                'b2b_moq' => 6,
                'stock_quantity' => 80,
                'category' => 'Home & Kitchen',
                'brand' => 'BrewMaster',
                'model' => 'BM-501',
                'specifications' => ['capacity' => '12 cups', 'features' => 'Programmable, Thermal Carafe, Smart Control', 'material' => 'Stainless Steel'],
                'images' => [
                    'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&auto=format&fit=crop&crop=top'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.8,
                'verification_status' => 'approved',
                'category_id' => 10,
            ],

            // Sports & Outdoors
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Professional Yoga Mat',
                'slug' => 'professional-yoga-mat',
                'description' => 'Eco-friendly yoga mat with non-slip surface and carrying strap.',
                'b2c_price' => 39.99,
                'b2c_compare_price' => 59.99,
                'b2b_price' => 29.99,
                'b2b_moq' => 10,
                'stock_quantity' => 100,
                'category' => 'Sports & Outdoors',
                'brand' => 'YogaLife',
                'model' => 'YM-201',
                'specifications' => ['material' => 'Eco-friendly TPE', 'thickness' => '6mm', 'size' => '72" x 24"', 'features' => 'Non-slip, Carrying Strap'],
                'images' => [
                    'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=600&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=600&auto=format&fit=crop&crop=right'
                ],
                'status' => 'active',
                'is_featured' => false,
                'rating' => 4.5,
                'verification_status' => 'approved',
                'category_id' => 11, // Assuming 11 is for Sports & Outdoors
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Running Shoes - Men',
                'slug' => 'running-shoes-men',
                'description' => 'Lightweight running shoes with cushioning and breathable mesh upper.',
                'b2c_price' => 79.99,
                'b2c_compare_price' => 99.99,
                'b2b_price' => 64.99,
                'b2b_moq' => 8,
                'stock_quantity' => 120,
                'category' => 'Sports & Outdoors',
                'brand' => 'RunFast',
                'model' => 'RS-301',
                'specifications' => ['material' => 'Mesh, Rubber', 'cushioning' => 'EVA Foam', 'weight' => '280g', 'colors' => 'Black/Blue, White/Red'],
                'images' => [
                    'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&crop=left'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.6,
                'verification_status' => 'approved',
                'category_id' => 11,
            ],

            // Beauty & Personal Care
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Skincare Gift Set',
                'slug' => 'skincare-gift-set',
                'description' => 'Complete skincare set with cleanser, toner, moisturizer, and serum.',
                'b2c_price' => 69.99,
                'b2c_compare_price' => 89.99,
                'b2b_price' => 54.99,
                'b2b_moq' => 6,
                'stock_quantity' => 90,
                'category' => 'Beauty & Personal Care',
                'brand' => 'SkinPure',
                'model' => 'SGS-401',
                'specifications' => ['items' => '5 pieces', 'skin_type' => 'All Types', 'features' => 'Natural Ingredients, Cruelty-free'],
                'images' => [
                    'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&auto=format&fit=crop&crop=top'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.7,
                'verification_status' => 'approved',
                'category_id' => 12, // Assuming 12 is for Beauty & Personal Care
            ],

            // Books
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Bestseller Novel Collection',
                'slug' => 'bestseller-novel-collection',
                'description' => 'Set of 3 bestselling novels from award-winning authors.',
                'b2c_price' => 34.99,
                'b2c_compare_price' => 49.99,
                'b2b_price' => 27.99,
                'b2b_moq' => 15,
                'stock_quantity' => 200,
                'category' => 'Books',
                'brand' => 'BookHouse',
                'model' => 'BC-301',
                'specifications' => ['books' => '3', 'format' => 'Hardcover', 'genre' => 'Fiction, Mystery'],
                'images' => [
                    'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&auto=format&fit=crop&crop=right'
                ],
                'status' => 'active',
                'is_featured' => false,
                'rating' => 4.8,
                'verification_status' => 'approved',
                'category_id' => 13, // Assuming 13 is for Books
            ],
        ];

        // Original Products (Printer-related)
        $originalProducts = [
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Jet Black Ink Cartridge',
                'slug' => 'jet-black-ink-cartridge',
                'description' => 'High quality black ink cartridge for Jet printers.',
                'b2c_price' => 19.99,
                'b2c_compare_price' => 24.99,
                'b2b_price' => 15.99,
                'b2b_moq' => 10,
                'stock_quantity' => 100,
                'category' => 'Ink Cartridges',
                'brand' => 'JetBrand',
                'model' => 'JB-1000',
                'specifications' => ['color' => 'Black', 'capacity' => '20ml'],
                'images' => [
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=600&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=600&auto=format&fit=crop&crop=center'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.5,
                'verification_status' => 'approved',
                'category_id' => 1,
            ],
            [
                'seller_id' => 4,
                'manufacturer_id' => null,
                'owner_type' => 'App\\Models\\Seller',
                'owner_id' => 4,
                'name' => 'Premium Photo Paper',
                'slug' => 'premium-photo-paper',
                'description' => 'Glossy photo paper for professional prints.',
                'b2c_price' => 12.99,
                'b2c_compare_price' => 15.99,
                'b2b_price' => 10.99,
                'b2b_moq' => 20,
                'stock_quantity' => 200,
                'category' => 'Paper',
                'brand' => 'PhotoPro',
                'model' => 'PP-300',
                'specifications' => ['size' => 'A4', 'finish' => 'Glossy'],
                'images' => [
                    'https://images.unsplash.com/photo-1509869175650-a1d97972541a?w=600&auto=format&fit=crop',
                    'https://images.unsplash.com/photo-1509869175650-a1d97972541a?w=600&auto=format&fit=crop&crop=right'
                ],
                'status' => 'active',
                'is_featured' => true,
                'rating' => 4.8,
                'verification_status' => 'approved',
                'category_id' => 2,
            ],
            // ... Keep the rest of your original products here
        ];

        // Combine all products
        $allProducts = array_merge($products, $originalProducts);

        foreach ($allProducts as $product) {
            Product::create($product);
        }
    }
}