<?php

namespace App\Http\Controllers\Accountant;

use App\Http\Controllers\Controller;
use App\Models\Order;
use App\Models\OrderStatus;
use Barryvdh\DomPDF\Facade\Pdf;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Log;

class AccountantOrderController extends Controller
{
    public function index()
    {
        // Get orders that are in accountant_billing stage
        $orders = Auth::user()
            ->accountant
            ->seller
            ->orders()
            ->whereHas('statuses', function($query) {
                $query->where('stage', 'accountant_billing')
                      ->where('status', 'in_progress');
            })
            ->orderBy('id', 'desc')
            ->paginate(10);

        return view('accountant.orders.index', compact('orders'));
    }

    public function show(int $id)
    {
        $order = Order::findOrFail($id);
        // $this->authorize('view', $order);

        return view('accountant.orders.show', compact('order'));
    }

    public function confirm($id)
    {
        $order = Order::with('orderItems.product')->findOrFail($id);

        // Validate current stage - should be in accountant_billing
        $currentStatus = $order->statuses()->where('stage', 'accountant_billing')->first();
        if (!$currentStatus || $currentStatus->status !== 'in_progress') {
            return redirect()->back()->with('error', 'Order is not in accountant billing stage.');
        }

        return view('accountant.orders.invoicing', compact('order'));
    }

    public function saveInvoice($id)
    {
        $order = Order::with('orderItems.product')->findOrFail($id);

        // Validate current stage - should be in accountant_billing
        $currentStatus = $order->statuses()->where('stage', 'accountant_billing')->first();
        if (!$currentStatus || $currentStatus->status !== 'in_progress') {
            return redirect()->back()->with('error', 'Order is not in accountant billing stage.');
        }

        // Calculate total if not present
        $totalAmount = $order->orderItems->sum(function ($item) {
            return $item->price * $item->quantity;
        });

        $data = [
            'order' => $order,
            'total_amount' => $totalAmount,
        ];

        // Generate the PDF
        $pdf = Pdf::loadView('accountant.orders.invoice', $data)
            ->setPaper('a4', 'portrait');

        $filename = 'invoice-order-' . $order->id . '.pdf';

        $order->invoice = $filename;
        $order->invoice_date = Carbon::now()->toDateTimeString();
        $order->status = 'Invoiced - Ready for Dispatch';
        $order->save();

        // Audit logging
        Log::info('Invoice generated by accountant', [
            'order_id' => $order->id,
            'accountant_id' => Auth::id(),
            'invoice_filename' => $filename,
            'timestamp' => now(),
        ]);

        // Mark accountant_billing as completed
        OrderStatus::where('order_id', $order->id)
            ->where('stage', 'accountant_billing')
            ->update([
                'status' => 'completed',
                'completed_at' => now(),
            ]);

        // Move to warehouse_dispatch stage
        OrderStatus::where('order_id', $order->id)
            ->where('stage', 'warehouse_dispatch')
            ->update([
                'status' => 'in_progress',
                'started_at' => now(),
            ]);

        // Save the PDF to storage
        Storage::put('public/invoices/' . $filename, $pdf->output());

        // Return the PDF for download
        return $pdf->download($filename);
    }
}
